version: '3.8'

services:
  web:
    container_name: warehouse-web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - warehouse_network

  api:
    container_name: warehouse-api
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "${PORT}:3000"
    volumes:
      - ./nginx/logs:/app/logs
    depends_on:
      - db
    networks:
      - warehouse_network

  db:
    container_name: warehouse-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: /var/lib/postgresql/data/pg
    volumes:
      - warehouse_db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - warehouse_network

networks:
  warehouse_network:
    name: warehouse_network

volumes:
  warehouse_db_data:
    driver: local